#!/bin/bash

# File path
BUTTON="/usr/bin/power-button"
RELEASE="/usr/bin/power-button-release"
# Check if the file exists
if [[ -f "$BUTTON" && -f "$RELEASE" ]]; then
    # Replace LONG_PRESS_THRESHOLD=2 with LONG_PRESS_THRESHOLD=0.1
    sed -i 's/^LONG_PRESS_THRESHOLD=2$/LONG_PRESS_THRESHOLD=0.1/' "$BUTTON"
	  # Always echo 1 to never sleep
	  sed -i 's/echo "0" > "\$POWER_BUTTON_STATE"/echo "1" > "\$POWER_BUTTON_STATE"/' "$RELEASE"
else
    exit 1
fi
